/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { ElementsRequest } from '../model/ElementsRequest';
import { ElementsResponse } from '../model/ElementsResponse';

/**
* Elements service.
* @module api/ElementsApi
* @version 4.0.3
*/
export class ElementsApi {
  /**
    * Constructs a new ElementsApi.
    * @alias module:api/ElementsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
     * Callback function to receive the result of the createOrUpdateElements operation.
     * @callback moduleapi/ElementsApi~createOrUpdateElementsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ElementsResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {module:model/ElementsRequest} body
     * @param {String} projectId
     * @param {String} refId
     * @param {Object} opts Optional parameters
     * @param {String} opts.overwrite
     * @param {module:api/ElementsApi~createOrUpdateElementsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  createOrUpdateElements(body, projectId, refId, opts, callback) {
    opts = opts || {};
    const postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error("Missing the required parameter 'body' when calling createOrUpdateElements");
    }
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling createOrUpdateElements");
    }
    // verify the required parameter 'refId' is set
    if (refId === undefined || refId === null) {
      throw new Error("Missing the required parameter 'refId' when calling createOrUpdateElements");
    }

    const pathParams = {
      projectId, refId,
    };
    const queryParams = {
      overwrite: opts.overwrite,
    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = ElementsResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/refs/{refId}/elements',
      'POST',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
  /**
     * Callback function to receive the result of the deleteElement operation.
     * @callback moduleapi/ElementsApi~deleteElementCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ElementsResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {String} projectId
     * @param {String} refId
     * @param {String} elementId
     * @param {module:api/ElementsApi~deleteElementCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  deleteElement(projectId, refId, elementId, callback) {
    const postBody = null;
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling deleteElement");
    }
    // verify the required parameter 'refId' is set
    if (refId === undefined || refId === null) {
      throw new Error("Missing the required parameter 'refId' when calling deleteElement");
    }
    // verify the required parameter 'elementId' is set
    if (elementId === undefined || elementId === null) {
      throw new Error("Missing the required parameter 'elementId' when calling deleteElement");
    }

    const pathParams = {
      projectId, refId, elementId,
    };
    const queryParams = {

    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = [];
    const accepts = ['application/json'];
    const returnType = ElementsResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/refs/{refId}/elements/{elementId}',
      'DELETE',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
  /**
     * Callback function to receive the result of the deleteElements operation.
     * @callback moduleapi/ElementsApi~deleteElementsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ElementsResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {module:model/ElementsRequest} body
     * @param {String} projectId
     * @param {String} refId
     * @param {module:api/ElementsApi~deleteElementsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  deleteElements(body, projectId, refId, callback) {
    const postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error("Missing the required parameter 'body' when calling deleteElements");
    }
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling deleteElements");
    }
    // verify the required parameter 'refId' is set
    if (refId === undefined || refId === null) {
      throw new Error("Missing the required parameter 'refId' when calling deleteElements");
    }

    const pathParams = {
      projectId, refId,
    };
    const queryParams = {

    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = ElementsResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/refs/{refId}/elements',
      'DELETE',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
  /**
     * Callback function to receive the result of the getAllElements operation.
     * @callback moduleapi/ElementsApi~getAllElementsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ElementsResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {String} projectId
     * @param {String} refId
     * @param {Object} opts Optional parameters
     * @param {String} opts.commitId
     * @param {module:api/ElementsApi~getAllElementsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  getAllElements(projectId, refId, opts, callback) {
    opts = opts || {};
    const postBody = null;
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling getAllElements");
    }
    // verify the required parameter 'refId' is set
    if (refId === undefined || refId === null) {
      throw new Error("Missing the required parameter 'refId' when calling getAllElements");
    }

    const pathParams = {
      projectId, refId,
    };
    const queryParams = {
      commitId: opts.commitId,
    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = [];
    const accepts = ['application/json', 'application/x-ndjson'];
    const returnType = ElementsResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/refs/{refId}/elements',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
  /**
     * Callback function to receive the result of the getElement operation.
     * @callback moduleapi/ElementsApi~getElementCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ElementsResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {String} projectId
     * @param {String} refId
     * @param {String} elementId
     * @param {Object} opts Optional parameters
     * @param {String} opts.commitId
     * @param {module:api/ElementsApi~getElementCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  getElement(projectId, refId, elementId, opts, callback) {
    opts = opts || {};
    const postBody = null;
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling getElement");
    }
    // verify the required parameter 'refId' is set
    if (refId === undefined || refId === null) {
      throw new Error("Missing the required parameter 'refId' when calling getElement");
    }
    // verify the required parameter 'elementId' is set
    if (elementId === undefined || elementId === null) {
      throw new Error("Missing the required parameter 'elementId' when calling getElement");
    }

    const pathParams = {
      projectId, refId, elementId,
    };
    const queryParams = {
      commitId: opts.commitId,
    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = [];
    const accepts = ['application/json'];
    const returnType = ElementsResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/refs/{refId}/elements/{elementId}',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
  /**
     * Callback function to receive the result of the getElements operation.
     * @callback moduleapi/ElementsApi~getElementsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ElementsResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {module:model/ElementsRequest} body
     * @param {String} projectId
     * @param {String} refId
     * @param {Object} opts Optional parameters
     * @param {String} opts.commitId
     * @param {module:api/ElementsApi~getElementsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  getElements(body, projectId, refId, opts, callback) {
    opts = opts || {};
    const postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error("Missing the required parameter 'body' when calling getElements");
    }
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling getElements");
    }
    // verify the required parameter 'refId' is set
    if (refId === undefined || refId === null) {
      throw new Error("Missing the required parameter 'refId' when calling getElements");
    }

    const pathParams = {
      projectId, refId,
    };
    const queryParams = {
      commitId: opts.commitId,
    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = ElementsResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/refs/{refId}/elements',
      'PUT',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
}
