/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { InlineResponse200 } from '../model/InlineResponse200';

/**
* MMSVersion service.
* @module api/MMSVersionApi
* @version 4.0.3
*/
export class MMSVersionApi {
  /**
    * Constructs a new MMSVersionApi.
    * @alias module:api/MMSVersionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
     * Callback function to receive the result of the getMMSVersion operation.
     * @callback moduleapi/MMSVersionApi~getMMSVersionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {module:api/MMSVersionApi~getMMSVersionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  getMMSVersion(callback) {
    const postBody = null;

    const pathParams = {

    };
    const queryParams = {

    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = [];
    const contentTypes = [];
    const accepts = ['application/json'];
    const returnType = InlineResponse200;

    return this.apiClient.callApi(
      '/mmsversion',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
}
