/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { WebhookRequest } from '../model/WebhookRequest';
import { WebhookResponse } from '../model/WebhookResponse';

/**
* Webhooks service.
* @module api/WebhooksApi
* @version 4.0.3
*/
export class WebhooksApi {
  /**
    * Constructs a new WebhooksApi.
    * @alias module:api/WebhooksApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
     * Callback function to receive the result of the createOrUpdateWebhooks operation.
     * @callback moduleapi/WebhooksApi~createOrUpdateWebhooksCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WebhookResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {module:model/WebhookRequest} body
     * @param {String} projectId
     * @param {module:api/WebhooksApi~createOrUpdateWebhooksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  createOrUpdateWebhooks(body, projectId, callback) {
    const postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error("Missing the required parameter 'body' when calling createOrUpdateWebhooks");
    }
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling createOrUpdateWebhooks");
    }

    const pathParams = {
      projectId,
    };
    const queryParams = {

    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = WebhookResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/webhooks',
      'POST',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
  /**
     * Callback function to receive the result of the deleteWebhooks operation.
     * @callback moduleapi/WebhooksApi~deleteWebhooksCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WebhookResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {module:model/WebhookRequest} body
     * @param {String} projectId
     * @param {module:api/WebhooksApi~deleteWebhooksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  deleteWebhooks(body, projectId, callback) {
    const postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error("Missing the required parameter 'body' when calling deleteWebhooks");
    }
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling deleteWebhooks");
    }

    const pathParams = {
      projectId,
    };
    const queryParams = {

    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = WebhookResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/webhooks',
      'DELETE',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
  /**
     * Callback function to receive the result of the getAllWebhooks operation.
     * @callback moduleapi/WebhooksApi~getAllWebhooksCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WebhookResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {String} projectId
     * @param {module:api/WebhooksApi~getAllWebhooksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  getAllWebhooks(projectId, callback) {
    const postBody = null;
    // verify the required parameter 'projectId' is set
    if (projectId === undefined || projectId === null) {
      throw new Error("Missing the required parameter 'projectId' when calling getAllWebhooks");
    }

    const pathParams = {
      projectId,
    };
    const queryParams = {

    };
    const headerParams = {

    };
    const formParams = {

    };

    const authNames = ['basicAuth', 'bearerToken'];
    const contentTypes = [];
    const accepts = ['application/json'];
    const returnType = WebhookResponse;

    return this.apiClient.callApi(
      '/projects/{projectId}/webhooks',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback,
    );
  }
}
