/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from './ApiClient';
import { BasicSearchRequest } from './model/BasicSearchRequest';
import { Commit } from './model/Commit';
import { CommitsRequest } from './model/CommitsRequest';
import { CommitsResponse } from './model/CommitsResponse';
import { DocumentsResponse } from './model/DocumentsResponse';
import { Element } from './model/Element';
import { ElementVersion } from './model/ElementVersion';
import { ElementsElementIdBody } from './model/ElementsElementIdBody';
import { ElementsRequest } from './model/ElementsRequest';
import { ElementsResponse } from './model/ElementsResponse';
import { ElementsSearchResponse } from './model/ElementsSearchResponse';
import { GroupResponse } from './model/GroupResponse';
import { GroupUpdateRequest } from './model/GroupUpdateRequest';
import { GroupUpdateResponse } from './model/GroupUpdateResponse';
import { GroupsResponse } from './model/GroupsResponse';
import { InlineResponse200 } from './model/InlineResponse200';
import { JwtAuthenticationRequest } from './model/JwtAuthenticationRequest';
import { JwtAuthenticationResponse } from './model/JwtAuthenticationResponse';
import { JwtTokenValidationResponse } from './model/JwtTokenValidationResponse';
import { Mount } from './model/Mount';
import { MountsResponse } from './model/MountsResponse';
import { NotebooksRequest } from './model/NotebooksRequest';
import { NotebooksResponse } from './model/NotebooksResponse';
import { Org } from './model/Org';
import { OrganizationsRequest } from './model/OrganizationsRequest';
import { OrganizationsResponse } from './model/OrganizationsResponse';
import { Permission } from './model/Permission';
import { PermissionLookup } from './model/PermissionLookup';
import { PermissionLookupRequest } from './model/PermissionLookupRequest';
import { PermissionLookupResponse } from './model/PermissionLookupResponse';
import { PermissionResponse } from './model/PermissionResponse';
import { PermissionUpdate } from './model/PermissionUpdate';
import { PermissionUpdateRequest } from './model/PermissionUpdateRequest';
import { PermissionUpdateResponse } from './model/PermissionUpdateResponse';
import { PermissionUpdatesResponse } from './model/PermissionUpdatesResponse';
import { PermissionsRequest } from './model/PermissionsRequest';
import { PermissionsResponse } from './model/PermissionsResponse';
import { Project } from './model/Project';
import { ProjectsRequest } from './model/ProjectsRequest';
import { ProjectsResponse } from './model/ProjectsResponse';
import { Ref } from './model/Ref';
import { RefsRequest } from './model/RefsRequest';
import { RefsResponse } from './model/RefsResponse';
import { Rejection } from './model/Rejection';
import { Schema } from './model/Schema';
import { SchemasResponse } from './model/SchemasResponse';
import { User } from './model/User';
import { UserCreateRequest } from './model/UserCreateRequest';
import { UsersResponse } from './model/UsersResponse';
import { ViewGroupsResponse } from './model/ViewGroupsResponse';
import { Webhook } from './model/Webhook';
import { WebhookRequest } from './model/WebhookRequest';
import { WebhookResponse } from './model/WebhookResponse';
import { ArtifactsApi } from './api/ArtifactsApi';
import { AuthApi } from './api/AuthApi';
import { CommitsApi } from './api/CommitsApi';
import { ElementsApi } from './api/ElementsApi';
import { GroupsApi } from './api/GroupsApi';
import { MMSVersionApi } from './api/MMSVersionApi';
import { NotebooksApi } from './api/NotebooksApi';
import { OrgsApi } from './api/OrgsApi';
import { ProjectsApi } from './api/ProjectsApi';
import { RefsApi } from './api/RefsApi';
import { SearchApi } from './api/SearchApi';
import { ViewsApi } from './api/ViewsApi';
import { WebhooksApi } from './api/WebhooksApi';

/**
* Documentation_for_MMS_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MmsReferenceImplementationApi = require('index'); // See note below*.
* var xxxSvc = new MmsReferenceImplementationApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MmsReferenceImplementationApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MmsReferenceImplementationApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MmsReferenceImplementationApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 4.0.3
*/
export {
  /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
  ApiClient,

  /**
     * The BasicSearchRequest model constructor.
     * @property {module:model/BasicSearchRequest}
     */
  BasicSearchRequest,

  /**
     * The Commit model constructor.
     * @property {module:model/Commit}
     */
  Commit,

  /**
     * The CommitsRequest model constructor.
     * @property {module:model/CommitsRequest}
     */
  CommitsRequest,

  /**
     * The CommitsResponse model constructor.
     * @property {module:model/CommitsResponse}
     */
  CommitsResponse,

  /**
     * The DocumentsResponse model constructor.
     * @property {module:model/DocumentsResponse}
     */
  DocumentsResponse,

  /**
     * The Element model constructor.
     * @property {module:model/Element}
     */
  Element,

  /**
     * The ElementVersion model constructor.
     * @property {module:model/ElementVersion}
     */
  ElementVersion,

  /**
     * The ElementsElementIdBody model constructor.
     * @property {module:model/ElementsElementIdBody}
     */
  ElementsElementIdBody,

  /**
     * The ElementsRequest model constructor.
     * @property {module:model/ElementsRequest}
     */
  ElementsRequest,

  /**
     * The ElementsResponse model constructor.
     * @property {module:model/ElementsResponse}
     */
  ElementsResponse,

  /**
     * The ElementsSearchResponse model constructor.
     * @property {module:model/ElementsSearchResponse}
     */
  ElementsSearchResponse,

  /**
     * The GroupResponse model constructor.
     * @property {module:model/GroupResponse}
     */
  GroupResponse,

  /**
     * The GroupUpdateRequest model constructor.
     * @property {module:model/GroupUpdateRequest}
     */
  GroupUpdateRequest,

  /**
     * The GroupUpdateResponse model constructor.
     * @property {module:model/GroupUpdateResponse}
     */
  GroupUpdateResponse,

  /**
     * The GroupsResponse model constructor.
     * @property {module:model/GroupsResponse}
     */
  GroupsResponse,

  /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
  InlineResponse200,

  /**
     * The JwtAuthenticationRequest model constructor.
     * @property {module:model/JwtAuthenticationRequest}
     */
  JwtAuthenticationRequest,

  /**
     * The JwtAuthenticationResponse model constructor.
     * @property {module:model/JwtAuthenticationResponse}
     */
  JwtAuthenticationResponse,

  /**
     * The JwtTokenValidationResponse model constructor.
     * @property {module:model/JwtTokenValidationResponse}
     */
  JwtTokenValidationResponse,

  /**
     * The Mount model constructor.
     * @property {module:model/Mount}
     */
  Mount,

  /**
     * The MountsResponse model constructor.
     * @property {module:model/MountsResponse}
     */
  MountsResponse,

  /**
     * The NotebooksRequest model constructor.
     * @property {module:model/NotebooksRequest}
     */
  NotebooksRequest,

  /**
     * The NotebooksResponse model constructor.
     * @property {module:model/NotebooksResponse}
     */
  NotebooksResponse,

  /**
     * The Org model constructor.
     * @property {module:model/Org}
     */
  Org,

  /**
     * The OrganizationsRequest model constructor.
     * @property {module:model/OrganizationsRequest}
     */
  OrganizationsRequest,

  /**
     * The OrganizationsResponse model constructor.
     * @property {module:model/OrganizationsResponse}
     */
  OrganizationsResponse,

  /**
     * The Permission model constructor.
     * @property {module:model/Permission}
     */
  Permission,

  /**
     * The PermissionLookup model constructor.
     * @property {module:model/PermissionLookup}
     */
  PermissionLookup,

  /**
     * The PermissionLookupRequest model constructor.
     * @property {module:model/PermissionLookupRequest}
     */
  PermissionLookupRequest,

  /**
     * The PermissionLookupResponse model constructor.
     * @property {module:model/PermissionLookupResponse}
     */
  PermissionLookupResponse,

  /**
     * The PermissionResponse model constructor.
     * @property {module:model/PermissionResponse}
     */
  PermissionResponse,

  /**
     * The PermissionUpdate model constructor.
     * @property {module:model/PermissionUpdate}
     */
  PermissionUpdate,

  /**
     * The PermissionUpdateRequest model constructor.
     * @property {module:model/PermissionUpdateRequest}
     */
  PermissionUpdateRequest,

  /**
     * The PermissionUpdateResponse model constructor.
     * @property {module:model/PermissionUpdateResponse}
     */
  PermissionUpdateResponse,

  /**
     * The PermissionUpdatesResponse model constructor.
     * @property {module:model/PermissionUpdatesResponse}
     */
  PermissionUpdatesResponse,

  /**
     * The PermissionsRequest model constructor.
     * @property {module:model/PermissionsRequest}
     */
  PermissionsRequest,

  /**
     * The PermissionsResponse model constructor.
     * @property {module:model/PermissionsResponse}
     */
  PermissionsResponse,

  /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
  Project,

  /**
     * The ProjectsRequest model constructor.
     * @property {module:model/ProjectsRequest}
     */
  ProjectsRequest,

  /**
     * The ProjectsResponse model constructor.
     * @property {module:model/ProjectsResponse}
     */
  ProjectsResponse,

  /**
     * The Ref model constructor.
     * @property {module:model/Ref}
     */
  Ref,

  /**
     * The RefsRequest model constructor.
     * @property {module:model/RefsRequest}
     */
  RefsRequest,

  /**
     * The RefsResponse model constructor.
     * @property {module:model/RefsResponse}
     */
  RefsResponse,

  /**
     * The Rejection model constructor.
     * @property {module:model/Rejection}
     */
  Rejection,

  /**
     * The Schema model constructor.
     * @property {module:model/Schema}
     */
  Schema,

  /**
     * The SchemasResponse model constructor.
     * @property {module:model/SchemasResponse}
     */
  SchemasResponse,

  /**
     * The User model constructor.
     * @property {module:model/User}
     */
  User,

  /**
     * The UserCreateRequest model constructor.
     * @property {module:model/UserCreateRequest}
     */
  UserCreateRequest,

  /**
     * The UsersResponse model constructor.
     * @property {module:model/UsersResponse}
     */
  UsersResponse,

  /**
     * The ViewGroupsResponse model constructor.
     * @property {module:model/ViewGroupsResponse}
     */
  ViewGroupsResponse,

  /**
     * The Webhook model constructor.
     * @property {module:model/Webhook}
     */
  Webhook,

  /**
     * The WebhookRequest model constructor.
     * @property {module:model/WebhookRequest}
     */
  WebhookRequest,

  /**
     * The WebhookResponse model constructor.
     * @property {module:model/WebhookResponse}
     */
  WebhookResponse,

  /**
    * The ArtifactsApi service constructor.
    * @property {module:api/ArtifactsApi}
    */
  ArtifactsApi,

  /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
  AuthApi,

  /**
    * The CommitsApi service constructor.
    * @property {module:api/CommitsApi}
    */
  CommitsApi,

  /**
    * The ElementsApi service constructor.
    * @property {module:api/ElementsApi}
    */
  ElementsApi,

  /**
    * The GroupsApi service constructor.
    * @property {module:api/GroupsApi}
    */
  GroupsApi,

  /**
    * The MMSVersionApi service constructor.
    * @property {module:api/MMSVersionApi}
    */
  MMSVersionApi,

  /**
    * The NotebooksApi service constructor.
    * @property {module:api/NotebooksApi}
    */
  NotebooksApi,

  /**
    * The OrgsApi service constructor.
    * @property {module:api/OrgsApi}
    */
  OrgsApi,

  /**
    * The ProjectsApi service constructor.
    * @property {module:api/ProjectsApi}
    */
  ProjectsApi,

  /**
    * The RefsApi service constructor.
    * @property {module:api/RefsApi}
    */
  RefsApi,

  /**
    * The SearchApi service constructor.
    * @property {module:api/SearchApi}
    */
  SearchApi,

  /**
    * The ViewsApi service constructor.
    * @property {module:api/ViewsApi}
    */
  ViewsApi,

  /**
    * The WebhooksApi service constructor.
    * @property {module:api/WebhooksApi}
    */
  WebhooksApi,
};
