/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The BasicSearchRequest model module.
 * @module model/BasicSearchRequest
 * @version 4.0.3
 */
export class BasicSearchRequest {
  /**
   * Constructs a new <code>BasicSearchRequest</code>.
   * @alias module:model/BasicSearchRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BasicSearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BasicSearchRequest} obj Optional instance to populate.
   * @return {module:model/BasicSearchRequest} The populated <code>BasicSearchRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BasicSearchRequest();
      if (data.hasOwnProperty('params')) obj.params = ApiClient.convertToType(data.params, { String: 'String' });
      if (data.hasOwnProperty('recurse')) obj.recurse = ApiClient.convertToType(data.recurse, { String: 'String' });
      if (data.hasOwnProperty('from')) obj.from = ApiClient.convertToType(data.from, 'Number');
      if (data.hasOwnProperty('size')) obj.size = ApiClient.convertToType(data.size, 'Number');
    }
    return obj;
  }
}

/**
 * @member {Object.<String, String>} params
 */
BasicSearchRequest.prototype.params = undefined;

/**
 * @member {Object.<String, String>} recurse
 */
BasicSearchRequest.prototype.recurse = undefined;

/**
 * @member {Number} from
 */
BasicSearchRequest.prototype.from = undefined;

/**
 * @member {Number} size
 */
BasicSearchRequest.prototype.size = undefined;
