/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Commit } from './Commit';

/**
 * The CommitsRequest model module.
 * @module model/CommitsRequest
 * @version 4.0.3
 */
export class CommitsRequest {
  /**
   * Constructs a new <code>CommitsRequest</code>.
   * @alias module:model/CommitsRequest
   * @class
   * @param commits {Array.<module:model/Commit>}
   */
  constructor(commits) {
    this.commits = commits;
  }

  /**
   * Constructs a <code>CommitsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommitsRequest} obj Optional instance to populate.
   * @return {module:model/CommitsRequest} The populated <code>CommitsRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CommitsRequest();
      if (data.hasOwnProperty('commits')) obj.commits = ApiClient.convertToType(data.commits, [Commit]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Commit>} commits
 */
CommitsRequest.prototype.commits = undefined;
