/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Commit } from './Commit';
import { Rejection } from './Rejection';

/**
 * The CommitsResponse model module.
 * @module model/CommitsResponse
 * @version 4.0.3
 */
export class CommitsResponse {
  /**
   * Constructs a new <code>CommitsResponse</code>.
   * @alias module:model/CommitsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CommitsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommitsResponse} obj Optional instance to populate.
   * @return {module:model/CommitsResponse} The populated <code>CommitsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CommitsResponse();
      if (data.hasOwnProperty('messages')) obj.messages = ApiClient.convertToType(data.messages, ['String']);
      if (data.hasOwnProperty('rejected')) obj.rejected = ApiClient.convertToType(data.rejected, [Rejection]);
      if (data.hasOwnProperty('commits')) obj.commits = ApiClient.convertToType(data.commits, [Commit]);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} messages
 */
CommitsResponse.prototype.messages = undefined;

/**
 * @member {Array.<module:model/Rejection>} rejected
 */
CommitsResponse.prototype.rejected = undefined;

/**
 * @member {Array.<module:model/Commit>} commits
 */
CommitsResponse.prototype.commits = undefined;
