/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Element } from './Element';
import { Rejection } from './Rejection';

/**
 * The ElementsResponse model module.
 * @module model/ElementsResponse
 * @version 4.0.3
 */
export class ElementsResponse {
  /**
   * Constructs a new <code>ElementsResponse</code>.
   * @alias module:model/ElementsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ElementsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ElementsResponse} obj Optional instance to populate.
   * @return {module:model/ElementsResponse} The populated <code>ElementsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ElementsResponse();
      if (data.hasOwnProperty('messages')) obj.messages = ApiClient.convertToType(data.messages, ['String']);
      if (data.hasOwnProperty('rejected')) obj.rejected = ApiClient.convertToType(data.rejected, [Rejection]);
      if (data.hasOwnProperty('elements')) obj.elements = ApiClient.convertToType(data.elements, [Element]);
      if (data.hasOwnProperty('commitId')) obj.commitId = ApiClient.convertToType(data.commitId, 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} messages
 */
ElementsResponse.prototype.messages = undefined;

/**
 * @member {Array.<module:model/Rejection>} rejected
 */
ElementsResponse.prototype.rejected = undefined;

/**
 * @member {Array.<module:model/Element>} elements
 */
ElementsResponse.prototype.elements = undefined;

/**
 * @member {String} commitId
 */
ElementsResponse.prototype.commitId = undefined;
