/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The ElementsElementIdBody model module.
 * @module model/ElementsElementIdBody
 * @version 4.0.3
 */
export class ElementsElementIdBody {
  /**
   * Constructs a new <code>ElementsElementIdBody</code>.
   * @alias module:model/ElementsElementIdBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ElementsElementIdBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ElementsElementIdBody} obj Optional instance to populate.
   * @return {module:model/ElementsElementIdBody} The populated <code>ElementsElementIdBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ElementsElementIdBody();
      if (data.hasOwnProperty('file')) obj.file = ApiClient.convertToType(data.file, 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Blob} file
 */
ElementsElementIdBody.prototype.file = undefined;
