/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The Element model module.
 * @module model/Element
 * @version 4.0.3
 */
export class Element {
  /**
   * Constructs a new <code>Element</code>.
   * @alias module:model/Element
   * @class
   * @extends
   */
  constructor() {
  }

  /**
   * Constructs a <code>Element</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Element} obj Optional instance to populate.
   * @return {module:model/Element} The populated <code>Element</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Element();
      ApiClient.constructFromObject(data, obj, '');
    }
    return obj;
  }
}
