/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Element } from './Element';

/**
 * The ElementsRequest model module.
 * @module model/ElementsRequest
 * @version 4.0.3
 */
export class ElementsRequest {
  /**
   * Constructs a new <code>ElementsRequest</code>.
   * @alias module:model/ElementsRequest
   * @class
   * @param elements {Array.<module:model/Element>}
   */
  constructor(elements) {
    this.elements = elements;
  }

  /**
   * Constructs a <code>ElementsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ElementsRequest} obj Optional instance to populate.
   * @return {module:model/ElementsRequest} The populated <code>ElementsRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ElementsRequest();
      if (data.hasOwnProperty('source')) obj.source = ApiClient.convertToType(data.source, 'String');
      if (data.hasOwnProperty('comment')) obj.comment = ApiClient.convertToType(data.comment, 'String');
      if (data.hasOwnProperty('elements')) obj.elements = ApiClient.convertToType(data.elements, [Element]);
    }
    return obj;
  }
}

/**
 * @member {String} source
 */
ElementsRequest.prototype.source = undefined;

/**
 * @member {String} comment
 */
ElementsRequest.prototype.comment = undefined;

/**
 * @member {Array.<module:model/Element>} elements
 */
ElementsRequest.prototype.elements = undefined;
