/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The ElementVersion model module.
 * @module model/ElementVersion
 * @version 4.0.3
 */
export class ElementVersion {
  /**
   * Constructs a new <code>ElementVersion</code>.
   * @alias module:model/ElementVersion
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ElementVersion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ElementVersion} obj Optional instance to populate.
   * @return {module:model/ElementVersion} The populated <code>ElementVersion</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ElementVersion();
      if (data.hasOwnProperty('type')) obj.type = ApiClient.convertToType(data.type, 'String');
      if (data.hasOwnProperty('id')) obj.id = ApiClient.convertToType(data.id, 'String');
      if (data.hasOwnProperty('_previousDocId')) obj.previousDocId = ApiClient.convertToType(data._previousDocId, 'String');
      if (data.hasOwnProperty('_docId')) obj.docId = ApiClient.convertToType(data._docId, 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
ElementVersion.prototype.type = undefined;

/**
 * @member {String} id
 */
ElementVersion.prototype.id = undefined;

/**
 * @member {String} previousDocId
 */
ElementVersion.prototype.previousDocId = undefined;

/**
 * @member {String} docId
 */
ElementVersion.prototype.docId = undefined;
