/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The GroupUpdateResponse model module.
 * @module model/GroupUpdateResponse
 * @version 4.0.3
 */
export class GroupUpdateResponse {
  /**
   * Constructs a new <code>GroupUpdateResponse</code>.
   * @alias module:model/GroupUpdateResponse
   * @class
   * @param group {String}
   */
  constructor(group) {
    this.group = group;
  }

  /**
   * Constructs a <code>GroupUpdateResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupUpdateResponse} obj Optional instance to populate.
   * @return {module:model/GroupUpdateResponse} The populated <code>GroupUpdateResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupUpdateResponse();
      if (data.hasOwnProperty('group')) obj.group = ApiClient.convertToType(data.group, 'String');
      if (data.hasOwnProperty('added')) obj.added = ApiClient.convertToType(data.added, ['String']);
      if (data.hasOwnProperty('removed')) obj.removed = ApiClient.convertToType(data.removed, ['String']);
      if (data.hasOwnProperty('rejected')) obj.rejected = ApiClient.convertToType(data.rejected, ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} group
 */
GroupUpdateResponse.prototype.group = undefined;

/**
 * @member {Array.<String>} added
 */
GroupUpdateResponse.prototype.added = undefined;

/**
 * @member {Array.<String>} removed
 */
GroupUpdateResponse.prototype.removed = undefined;

/**
 * @member {Array.<String>} rejected
 */
GroupUpdateResponse.prototype.rejected = undefined;
