/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The GroupResponse model module.
 * @module model/GroupResponse
 * @version 4.0.3
 */
export class GroupResponse {
  /**
   * Constructs a new <code>GroupResponse</code>.
   * @alias module:model/GroupResponse
   * @class
   * @param group {String}
   */
  constructor(group) {
    this.group = group;
  }

  /**
   * Constructs a <code>GroupResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupResponse} obj Optional instance to populate.
   * @return {module:model/GroupResponse} The populated <code>GroupResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupResponse();
      if (data.hasOwnProperty('group')) obj.group = ApiClient.convertToType(data.group, 'String');
      if (data.hasOwnProperty('users')) obj.users = ApiClient.convertToType(data.users, ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} group
 */
GroupResponse.prototype.group = undefined;

/**
 * @member {Array.<String>} users
 */
GroupResponse.prototype.users = undefined;
