/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The GroupsResponse model module.
 * @module model/GroupsResponse
 * @version 4.0.3
 */
export class GroupsResponse {
  /**
   * Constructs a new <code>GroupsResponse</code>.
   * @alias module:model/GroupsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GroupsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupsResponse} obj Optional instance to populate.
   * @return {module:model/GroupsResponse} The populated <code>GroupsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupsResponse();
      if (data.hasOwnProperty('groups')) obj.groups = ApiClient.convertToType(data.groups, ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} groups
 */
GroupsResponse.prototype.groups = undefined;
