/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The GroupUpdateRequest model module.
 * @module model/GroupUpdateRequest
 * @version 4.0.3
 */
export class GroupUpdateRequest {
  /**
   * Constructs a new <code>GroupUpdateRequest</code>.
   * @alias module:model/GroupUpdateRequest
   * @class
   * @param action {module:model/GroupUpdateRequest.ActionEnum}
   * @param users {Array.<String>}
   */
  constructor(action, users) {
    this.action = action;
    this.users = users;
  }

  /**
   * Constructs a <code>GroupUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupUpdateRequest} obj Optional instance to populate.
   * @return {module:model/GroupUpdateRequest} The populated <code>GroupUpdateRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupUpdateRequest();
      if (data.hasOwnProperty('action')) obj.action = ApiClient.convertToType(data.action, 'String');
      if (data.hasOwnProperty('users')) obj.users = ApiClient.convertToType(data.users, ['String']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
GroupUpdateRequest.ActionEnum = {
  /**
   * value: "ADD"
   * @const
   */
  ADD: 'ADD',

  /**
   * value: "REMOVE"
   * @const
   */
  REMOVE: 'REMOVE',
};
/**
 * @member {module:model/GroupUpdateRequest.ActionEnum} action
 */
GroupUpdateRequest.prototype.action = undefined;

/**
 * @member {Array.<String>} users
 */
GroupUpdateRequest.prototype.users = undefined;
