/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The JwtAuthenticationRequest model module.
 * @module model/JwtAuthenticationRequest
 * @version 4.0.3
 */
export class JwtAuthenticationRequest {
  /**
   * Constructs a new <code>JwtAuthenticationRequest</code>.
   * @alias module:model/JwtAuthenticationRequest
   * @class
   * @param username {String}
   * @param password {String}
   */
  constructor(username, password) {
    this.username = username;
    this.password = password;
  }

  /**
   * Constructs a <code>JwtAuthenticationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JwtAuthenticationRequest} obj Optional instance to populate.
   * @return {module:model/JwtAuthenticationRequest} The populated <code>JwtAuthenticationRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JwtAuthenticationRequest();
      if (data.hasOwnProperty('username')) obj.username = ApiClient.convertToType(data.username, 'String');
      if (data.hasOwnProperty('password')) obj.password = ApiClient.convertToType(data.password, 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
JwtAuthenticationRequest.prototype.username = undefined;

/**
 * @member {String} password
 */
JwtAuthenticationRequest.prototype.password = undefined;
