/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The JwtTokenValidationResponse model module.
 * @module model/JwtTokenValidationResponse
 * @version 4.0.3
 */
export class JwtTokenValidationResponse {
  /**
   * Constructs a new <code>JwtTokenValidationResponse</code>.
   * @alias module:model/JwtTokenValidationResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JwtTokenValidationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JwtTokenValidationResponse} obj Optional instance to populate.
   * @return {module:model/JwtTokenValidationResponse} The populated <code>JwtTokenValidationResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JwtTokenValidationResponse();
      if (data.hasOwnProperty('username')) obj.username = ApiClient.convertToType(data.username, 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
JwtTokenValidationResponse.prototype.username = undefined;
