/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Element } from './Element';

/**
 * The NotebooksRequest model module.
 * @module model/NotebooksRequest
 * @version 4.0.3
 */
export class NotebooksRequest {
  /**
   * Constructs a new <code>NotebooksRequest</code>.
   * @alias module:model/NotebooksRequest
   * @class
   * @param notebooks {Array.<module:model/Element>}
   */
  constructor(notebooks) {
    this.notebooks = notebooks;
  }

  /**
   * Constructs a <code>NotebooksRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotebooksRequest} obj Optional instance to populate.
   * @return {module:model/NotebooksRequest} The populated <code>NotebooksRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotebooksRequest();
      if (data.hasOwnProperty('source')) obj.source = ApiClient.convertToType(data.source, 'String');
      if (data.hasOwnProperty('comment')) obj.comment = ApiClient.convertToType(data.comment, 'String');
      if (data.hasOwnProperty('notebooks')) obj.notebooks = ApiClient.convertToType(data.notebooks, [Element]);
    }
    return obj;
  }
}

/**
 * @member {String} source
 */
NotebooksRequest.prototype.source = undefined;

/**
 * @member {String} comment
 */
NotebooksRequest.prototype.comment = undefined;

/**
 * @member {Array.<module:model/Element>} notebooks
 */
NotebooksRequest.prototype.notebooks = undefined;
