/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Permission } from './Permission';

/**
 * The PermissionUpdateRequest model module.
 * @module model/PermissionUpdateRequest
 * @version 4.0.3
 */
export class PermissionUpdateRequest {
  /**
   * Constructs a new <code>PermissionUpdateRequest</code>.
   * @alias module:model/PermissionUpdateRequest
   * @class
   * @param action {module:model/PermissionUpdateRequest.ActionEnum}
   * @param permissions {Array.<module:model/Permission>}
   */
  constructor(action, permissions) {
    this.action = action;
    this.permissions = permissions;
  }

  /**
   * Constructs a <code>PermissionUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionUpdateRequest} obj Optional instance to populate.
   * @return {module:model/PermissionUpdateRequest} The populated <code>PermissionUpdateRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PermissionUpdateRequest();
      if (data.hasOwnProperty('action')) obj.action = ApiClient.convertToType(data.action, 'String');
      if (data.hasOwnProperty('permissions')) obj.permissions = ApiClient.convertToType(data.permissions, [Permission]);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
PermissionUpdateRequest.ActionEnum = {
  /**
   * value: "MODIFY"
   * @const
   */
  MODIFY: 'MODIFY',

  /**
   * value: "REPLACE"
   * @const
   */
  REPLACE: 'REPLACE',

  /**
   * value: "REMOVE"
   * @const
   */
  REMOVE: 'REMOVE',
};
/**
 * @member {module:model/PermissionUpdateRequest.ActionEnum} action
 */
PermissionUpdateRequest.prototype.action = undefined;

/**
 * @member {Array.<module:model/Permission>} permissions
 */
PermissionUpdateRequest.prototype.permissions = undefined;
