/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { PermissionLookup } from './PermissionLookup';

/**
 * The PermissionLookupRequest model module.
 * @module model/PermissionLookupRequest
 * @version 4.0.3
 */
export class PermissionLookupRequest {
  /**
   * Constructs a new <code>PermissionLookupRequest</code>.
   * @alias module:model/PermissionLookupRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PermissionLookupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionLookupRequest} obj Optional instance to populate.
   * @return {module:model/PermissionLookupRequest} The populated <code>PermissionLookupRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PermissionLookupRequest();
      if (data.hasOwnProperty('lookups')) obj.lookups = ApiClient.convertToType(data.lookups, [PermissionLookup]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/PermissionLookup>} lookups
 */
PermissionLookupRequest.prototype.lookups = undefined;
