/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { PermissionUpdate } from './PermissionUpdate';

/**
 * The PermissionUpdateResponse model module.
 * @module model/PermissionUpdateResponse
 * @version 4.0.3
 */
export class PermissionUpdateResponse {
  /**
   * Constructs a new <code>PermissionUpdateResponse</code>.
   * @alias module:model/PermissionUpdateResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PermissionUpdateResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionUpdateResponse} obj Optional instance to populate.
   * @return {module:model/PermissionUpdateResponse} The populated <code>PermissionUpdateResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PermissionUpdateResponse();
      if (data.hasOwnProperty('permissionUpdates')) obj.permissionUpdates = ApiClient.convertToType(data.permissionUpdates, [PermissionUpdate]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/PermissionUpdate>} permissionUpdates
 */
PermissionUpdateResponse.prototype.permissionUpdates = undefined;
