/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Permission } from './Permission';

/**
 * The PermissionResponse model module.
 * @module model/PermissionResponse
 * @version 4.0.3
 */
export class PermissionResponse {
  /**
   * Constructs a new <code>PermissionResponse</code>.
   * @alias module:model/PermissionResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PermissionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionResponse} obj Optional instance to populate.
   * @return {module:model/PermissionResponse} The populated <code>PermissionResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PermissionResponse();
      if (data.hasOwnProperty('permissions')) obj.permissions = ApiClient.convertToType(data.permissions, [Permission]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Permission>} permissions
 */
PermissionResponse.prototype.permissions = undefined;
