/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { PermissionLookup } from './PermissionLookup';
import { Rejection } from './Rejection';

/**
 * The PermissionLookupResponse model module.
 * @module model/PermissionLookupResponse
 * @version 4.0.3
 */
export class PermissionLookupResponse {
  /**
   * Constructs a new <code>PermissionLookupResponse</code>.
   * @alias module:model/PermissionLookupResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PermissionLookupResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionLookupResponse} obj Optional instance to populate.
   * @return {module:model/PermissionLookupResponse} The populated <code>PermissionLookupResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PermissionLookupResponse();
      if (data.hasOwnProperty('messages')) obj.messages = ApiClient.convertToType(data.messages, ['String']);
      if (data.hasOwnProperty('rejected')) obj.rejected = ApiClient.convertToType(data.rejected, [Rejection]);
      if (data.hasOwnProperty('lookups')) obj.lookups = ApiClient.convertToType(data.lookups, [PermissionLookup]);
      if (data.hasOwnProperty('allPassed')) obj.allPassed = ApiClient.convertToType(data.allPassed, 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} messages
 */
PermissionLookupResponse.prototype.messages = undefined;

/**
 * @member {Array.<module:model/Rejection>} rejected
 */
PermissionLookupResponse.prototype.rejected = undefined;

/**
 * @member {Array.<module:model/PermissionLookup>} lookups
 */
PermissionLookupResponse.prototype.lookups = undefined;

/**
 * @member {Boolean} allPassed
 */
PermissionLookupResponse.prototype.allPassed = undefined;
