/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { PermissionUpdateRequest } from './PermissionUpdateRequest';

/**
 * The PermissionsRequest model module.
 * @module model/PermissionsRequest
 * @version 4.0.3
 */
export class PermissionsRequest {
  /**
   * Constructs a new <code>PermissionsRequest</code>.
   * @alias module:model/PermissionsRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PermissionsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionsRequest} obj Optional instance to populate.
   * @return {module:model/PermissionsRequest} The populated <code>PermissionsRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PermissionsRequest();
      if (data.hasOwnProperty('users')) obj.users = PermissionUpdateRequest.constructFromObject(data.users);
      if (data.hasOwnProperty('groups')) obj.groups = PermissionUpdateRequest.constructFromObject(data.groups);
      if (data.hasOwnProperty('inherit')) obj.inherit = ApiClient.convertToType(data.inherit, 'Boolean');
      if (data.hasOwnProperty('public')) obj._public = ApiClient.convertToType(data.public, 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/PermissionUpdateRequest} users
 */
PermissionsRequest.prototype.users = undefined;

/**
 * @member {module:model/PermissionUpdateRequest} groups
 */
PermissionsRequest.prototype.groups = undefined;

/**
 * @member {Boolean} inherit
 */
PermissionsRequest.prototype.inherit = undefined;

/**
 * @member {Boolean} _public
 */
PermissionsRequest.prototype._public = undefined;
