/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { PermissionUpdateResponse } from './PermissionUpdateResponse';

/**
 * The PermissionUpdatesResponse model module.
 * @module model/PermissionUpdatesResponse
 * @version 4.0.3
 */
export class PermissionUpdatesResponse {
  /**
   * Constructs a new <code>PermissionUpdatesResponse</code>.
   * @alias module:model/PermissionUpdatesResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PermissionUpdatesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionUpdatesResponse} obj Optional instance to populate.
   * @return {module:model/PermissionUpdatesResponse} The populated <code>PermissionUpdatesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PermissionUpdatesResponse();
      if (data.hasOwnProperty('inherit')) obj.inherit = ApiClient.convertToType(data.inherit, 'Boolean');
      if (data.hasOwnProperty('users')) obj.users = PermissionUpdateResponse.constructFromObject(data.users);
      if (data.hasOwnProperty('groups')) obj.groups = PermissionUpdateResponse.constructFromObject(data.groups);
      if (data.hasOwnProperty('public')) obj._public = ApiClient.convertToType(data.public, 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} inherit
 */
PermissionUpdatesResponse.prototype.inherit = undefined;

/**
 * @member {module:model/PermissionUpdateResponse} users
 */
PermissionUpdatesResponse.prototype.users = undefined;

/**
 * @member {module:model/PermissionUpdateResponse} groups
 */
PermissionUpdatesResponse.prototype.groups = undefined;

/**
 * @member {Boolean} _public
 */
PermissionUpdatesResponse.prototype._public = undefined;
