/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Project } from './Project';

/**
 * The ProjectsRequest model module.
 * @module model/ProjectsRequest
 * @version 4.0.3
 */
export class ProjectsRequest {
  /**
   * Constructs a new <code>ProjectsRequest</code>.
   * @alias module:model/ProjectsRequest
   * @class
   * @param projects {Array.<module:model/Project>}
   */
  constructor(projects) {
    this.projects = projects;
  }

  /**
   * Constructs a <code>ProjectsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectsRequest} obj Optional instance to populate.
   * @return {module:model/ProjectsRequest} The populated <code>ProjectsRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectsRequest();
      if (data.hasOwnProperty('projects')) obj.projects = ApiClient.convertToType(data.projects, [Project]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Project>} projects
 */
ProjectsRequest.prototype.projects = undefined;
