/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The Ref model module.
 * @module model/Ref
 * @version 4.0.3
 */
export class Ref {
  /**
   * Constructs a new <code>Ref</code>.
   * @alias module:model/Ref
   * @class
   * @extends
   */
  constructor() {
  }

  /**
   * Constructs a <code>Ref</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ref} obj Optional instance to populate.
   * @return {module:model/Ref} The populated <code>Ref</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Ref();
      ApiClient.constructFromObject(data, obj, '');
    }
    return obj;
  }
}
