/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Ref } from './Ref';
import { Rejection } from './Rejection';

/**
 * The RefsResponse model module.
 * @module model/RefsResponse
 * @version 4.0.3
 */
export class RefsResponse {
  /**
   * Constructs a new <code>RefsResponse</code>.
   * @alias module:model/RefsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RefsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RefsResponse} obj Optional instance to populate.
   * @return {module:model/RefsResponse} The populated <code>RefsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RefsResponse();
      if (data.hasOwnProperty('messages')) obj.messages = ApiClient.convertToType(data.messages, ['String']);
      if (data.hasOwnProperty('rejected')) obj.rejected = ApiClient.convertToType(data.rejected, [Rejection]);
      if (data.hasOwnProperty('refs')) obj.refs = ApiClient.convertToType(data.refs, [Ref]);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} messages
 */
RefsResponse.prototype.messages = undefined;

/**
 * @member {Array.<module:model/Rejection>} rejected
 */
RefsResponse.prototype.rejected = undefined;

/**
 * @member {Array.<module:model/Ref>} refs
 */
RefsResponse.prototype.refs = undefined;
