/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The Rejection model module.
 * @module model/Rejection
 * @version 4.0.3
 */
export class Rejection {
  /**
   * Constructs a new <code>Rejection</code>.
   * @alias module:model/Rejection
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Rejection</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Rejection} obj Optional instance to populate.
   * @return {module:model/Rejection} The populated <code>Rejection</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Rejection();
      if (data.hasOwnProperty('object')) obj._object = ApiClient.convertToType(data.object, Object);
      if (data.hasOwnProperty('code')) obj.code = ApiClient.convertToType(data.code, 'Number');
      if (data.hasOwnProperty('message')) obj.message = ApiClient.convertToType(data.message, 'String');
    }
    return obj;
  }
}

/**
 * @member {Object} _object
 */
Rejection.prototype._object = undefined;

/**
 * @member {Number} code
 */
Rejection.prototype.code = undefined;

/**
 * @member {String} message
 */
Rejection.prototype.message = undefined;
