/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Schema } from './Schema';

/**
 * The SchemasResponse model module.
 * @module model/SchemasResponse
 * @version 4.0.3
 */
export class SchemasResponse {
  /**
   * Constructs a new <code>SchemasResponse</code>.
   * @alias module:model/SchemasResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SchemasResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SchemasResponse} obj Optional instance to populate.
   * @return {module:model/SchemasResponse} The populated <code>SchemasResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SchemasResponse();
      if (data.hasOwnProperty('schemas')) obj.schemas = ApiClient.convertToType(data.schemas, [Schema]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Schema>} schemas
 */
SchemasResponse.prototype.schemas = undefined;
