/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 4.0.3
 */
export class User {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('username')) obj.username = ApiClient.convertToType(data.username, 'String');
      if (data.hasOwnProperty('email')) obj.email = ApiClient.convertToType(data.email, 'String');
      if (data.hasOwnProperty('firstName')) obj.firstName = ApiClient.convertToType(data.firstName, 'String');
      if (data.hasOwnProperty('lastName')) obj.lastName = ApiClient.convertToType(data.lastName, 'String');
      if (data.hasOwnProperty('admin')) obj.admin = ApiClient.convertToType(data.admin, 'Boolean');
      if (data.hasOwnProperty('password')) obj.password = ApiClient.convertToType(data.password, 'String');
      if (data.hasOwnProperty('enabled')) obj.enabled = ApiClient.convertToType(data.enabled, 'Boolean');
      if (data.hasOwnProperty('fullName')) obj.fullName = ApiClient.convertToType(data.fullName, 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
User.prototype.username = undefined;

/**
 * @member {String} email
 */
User.prototype.email = undefined;

/**
 * @member {String} firstName
 */
User.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
User.prototype.lastName = undefined;

/**
 * @member {Boolean} admin
 */
User.prototype.admin = undefined;

/**
 * @member {String} password
 */
User.prototype.password = undefined;

/**
 * @member {Boolean} enabled
 */
User.prototype.enabled = undefined;

/**
 * @member {String} fullName
 */
User.prototype.fullName = undefined;
