/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The UserCreateRequest model module.
 * @module model/UserCreateRequest
 * @version 4.0.3
 */
export class UserCreateRequest {
  /**
   * Constructs a new <code>UserCreateRequest</code>.
   * @alias module:model/UserCreateRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserCreateRequest} obj Optional instance to populate.
   * @return {module:model/UserCreateRequest} The populated <code>UserCreateRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserCreateRequest();
      if (data.hasOwnProperty('username')) obj.username = ApiClient.convertToType(data.username, 'String');
      if (data.hasOwnProperty('password')) obj.password = ApiClient.convertToType(data.password, 'String');
      if (data.hasOwnProperty('email')) obj.email = ApiClient.convertToType(data.email, 'String');
      if (data.hasOwnProperty('firstname')) obj.firstname = ApiClient.convertToType(data.firstname, 'String');
      if (data.hasOwnProperty('lastname')) obj.lastname = ApiClient.convertToType(data.lastname, 'String');
      if (data.hasOwnProperty('admin')) obj.admin = ApiClient.convertToType(data.admin, 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
UserCreateRequest.prototype.username = undefined;

/**
 * @member {String} password
 */
UserCreateRequest.prototype.password = undefined;

/**
 * @member {String} email
 */
UserCreateRequest.prototype.email = undefined;

/**
 * @member {String} firstname
 */
UserCreateRequest.prototype.firstname = undefined;

/**
 * @member {String} lastname
 */
UserCreateRequest.prototype.lastname = undefined;

/**
 * @member {Boolean} admin
 */
UserCreateRequest.prototype.admin = undefined;
