/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Element } from './Element';
import { Rejection } from './Rejection';

/**
 * The ViewGroupsResponse model module.
 * @module model/ViewGroupsResponse
 * @version 4.0.3
 */
export class ViewGroupsResponse {
  /**
   * Constructs a new <code>ViewGroupsResponse</code>.
   * @alias module:model/ViewGroupsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ViewGroupsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ViewGroupsResponse} obj Optional instance to populate.
   * @return {module:model/ViewGroupsResponse} The populated <code>ViewGroupsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ViewGroupsResponse();
      if (data.hasOwnProperty('messages')) obj.messages = ApiClient.convertToType(data.messages, ['String']);
      if (data.hasOwnProperty('rejected')) obj.rejected = ApiClient.convertToType(data.rejected, [Rejection]);
      if (data.hasOwnProperty('groups')) obj.groups = ApiClient.convertToType(data.groups, [Element]);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} messages
 */
ViewGroupsResponse.prototype.messages = undefined;

/**
 * @member {Array.<module:model/Rejection>} rejected
 */
ViewGroupsResponse.prototype.rejected = undefined;

/**
 * @member {Array.<module:model/Element>} groups
 */
ViewGroupsResponse.prototype.groups = undefined;
