/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Rejection } from './Rejection';
import { Webhook } from './Webhook';

/**
 * The WebhookResponse model module.
 * @module model/WebhookResponse
 * @version 4.0.3
 */
export class WebhookResponse {
  /**
   * Constructs a new <code>WebhookResponse</code>.
   * @alias module:model/WebhookResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WebhookResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookResponse} obj Optional instance to populate.
   * @return {module:model/WebhookResponse} The populated <code>WebhookResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WebhookResponse();
      if (data.hasOwnProperty('messages')) obj.messages = ApiClient.convertToType(data.messages, ['String']);
      if (data.hasOwnProperty('rejected')) obj.rejected = ApiClient.convertToType(data.rejected, [Rejection]);
      if (data.hasOwnProperty('webhooks')) obj.webhooks = ApiClient.convertToType(data.webhooks, [Webhook]);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} messages
 */
WebhookResponse.prototype.messages = undefined;

/**
 * @member {Array.<module:model/Rejection>} rejected
 */
WebhookResponse.prototype.rejected = undefined;

/**
 * @member {Array.<module:model/Webhook>} webhooks
 */
WebhookResponse.prototype.webhooks = undefined;
