/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';
import { Webhook } from './Webhook';

/**
 * The WebhookRequest model module.
 * @module model/WebhookRequest
 * @version 4.0.3
 */
export class WebhookRequest {
  /**
   * Constructs a new <code>WebhookRequest</code>.
   * @alias module:model/WebhookRequest
   * @class
   * @param webhooks {Array.<module:model/Webhook>}
   */
  constructor(webhooks) {
    this.webhooks = webhooks;
  }

  /**
   * Constructs a <code>WebhookRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookRequest} obj Optional instance to populate.
   * @return {module:model/WebhookRequest} The populated <code>WebhookRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WebhookRequest();
      if (data.hasOwnProperty('webhooks')) obj.webhooks = ApiClient.convertToType(data.webhooks, [Webhook]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Webhook>} webhooks
 */
WebhookRequest.prototype.webhooks = undefined;
