/*
 * MMS Reference Implementation API
 * Documentation for MMS API
 *
 * OpenAPI spec version: 4.0.3
 * Contact: mms@openmbee.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient';

/**
 * The Webhook model module.
 * @module model/Webhook
 * @version 4.0.3
 */
export class Webhook {
  /**
   * Constructs a new <code>Webhook</code>.
   * @alias module:model/Webhook
   * @class
   * @param url {String}
   */
  constructor(url) {
    this.url = url;
  }

  /**
   * Constructs a <code>Webhook</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Webhook} obj Optional instance to populate.
   * @return {module:model/Webhook} The populated <code>Webhook</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Webhook();
      if (data.hasOwnProperty('url')) obj.url = ApiClient.convertToType(data.url, 'String');
      if (data.hasOwnProperty('type')) obj.type = ApiClient.convertToType(data.type, 'String');
      if (data.hasOwnProperty('id')) obj.id = ApiClient.convertToType(data.id, 'String');
      if (data.hasOwnProperty('_projectId')) obj.projectId = ApiClient.convertToType(data._projectId, 'String');
      if (data.hasOwnProperty('_creator')) obj.creator = ApiClient.convertToType(data._creator, 'String');
      if (data.hasOwnProperty('_created')) obj.created = ApiClient.convertToType(data._created, 'String');
    }
    return obj;
  }
}

/**
 * @member {String} url
 */
Webhook.prototype.url = undefined;

/**
 * @member {String} type
 */
Webhook.prototype.type = undefined;

/**
 * @member {String} id
 */
Webhook.prototype.id = undefined;

/**
 * @member {String} projectId
 */
Webhook.prototype.projectId = undefined;

/**
 * @member {String} creator
 */
Webhook.prototype.creator = undefined;

/**
 * @member {String} created
 */
Webhook.prototype.created = undefined;
